// ==UserScript==
// @name        Bugzilla - Hide bots comments
// @namespace   SUSE SecTools
// @match       https://bugzilla.suse.com/show_bug.cgi?*
// @match       https://bugzilla.opensuse.org/show_bug.cgi?*
// @run-at      document-end
// @grant       none
// @version     1.3.1
// @author      gsonnu
// @description Hides bots comment in bugzilla by default. Also add links to quickly collapse or expand them as needed
// ==/UserScript==

(function() {
    const bots = {'bwiedemann+obsbugzillabot@suse.com': '',
                  'swamp@suse.de': '',
                  'smash_bz@suse.de': '',
                  'maint-coord+maintenance_robot@suse.de': '',
                  'maint-coord+maintenance-robot@suse.de': '',
                  'openqa-review@suse.de': '',
                  'bwiedemann@suse.com': 'This is an autogenerated message',
                  'okurz@suse.com': 'This is an autogenerated message',
                  'meissner@suse.com': /openSUSE-.*: An update/,
                  'autobugz': ''};

    const embargoes = 'This is an embargoed bug. This means that this information is not public.';


    // pre process list instead of doing it for every comment
    for (const user in bots) {
        let pattern = bots[user];

        if (pattern instanceof RegExp)
            bots[user] = (t) => pattern.test(t);
        else if (pattern === '')
            bots[user] = (t) => true;
        else
            bots[user] = (t) => t.startsWith(pattern);
    }

    let is_embargo = (t) => t.startsWith(embargoes);

    // start processing comments
    let botsComments = [];

    for (let c of document.querySelectorAll('.bz_comment_head')) {
        let user = c.querySelector('.bz_comment_user a.email')['href'].replace('mailto:', '');
        let is_bot = bots[user] || ((t) => false);
        let text = c.parentNode.querySelector('.bz_comment_text').textContent.trim()

        if (is_bot(text) || is_embargo(text))
            botsComments.push(c);
    }

    let actionList = document.querySelector('.bz_collapse_expand_comments');

    addListItem(actionList, 'Collapse All Bot Comments', hideAllBots);
    addListItem(actionList, 'Expand All Bot Comments', showAllBots);

    hideAllBots();

    function addListItem(parent, text, func) {
        let li = document.createElement('li');
        let a = document.createElement('a');

        a.setAttribute('href', '#');
        a.textContent = text;
        a.onclick = (e) => func()

        li.appendChild(a);
        parent.appendChild(li);
    }

    function hideAllBots() {
        botsComments.map((c) => {
            let action = c.querySelector('.bz_comment_actions a.bz_collapse_comment');
            action.textContent = action.textContent.replace('−', '+');
            c.parentElement.querySelector('.bz_comment_text').classList.add('collapsed');
        });

        return false;
    }

    function showAllBots() {
        botsComments.map((c) => {
            let action = c.querySelector('.bz_comment_actions a.bz_collapse_comment');
            action.textContent = action.textContent.replace('+', '−');
            c.parentElement.querySelector('.bz_comment_text').classList.remove('collapsed');
        });

        return false;
    }

})();
